# -*- coding: utf-8 -*-
"""Análise de Desempenho de Campanha Digital

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11u57k_hKbf-Y53w3xej3-VKWA_TCo1y6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

np.random.seed(42)

dados = {
    'data': pd.date_range(start='2023-01-01', periods=30, freq='D'),
    'visitas': np.random.randint(100, 500, size=30),
    'conversoes': np.random.randint(10, 50, size=30),
    'fonte_trafego': np.random.choice(['Orgânico', 'Pagos', 'Referências', 'Social', 'Email'], 30)
}

df = pd.DataFrame(dados)

df['taxa_conversao'] = (df['conversoes'] / df['visitas']) * 100

print(df.head())

desempenho = df.groupby('fonte_trafego').agg({
    'visitas': 'sum',
    'conversoes': 'sum',
    'taxa_conversao': 'mean'
}).reset_index()

plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
sns.barplot(x='fonte_trafego', y='visitas', data=desempenho, palette='viridis')
plt.title('Visitas por Fonte de Tráfego')
plt.ylabel('Total de Visitas')
plt.xlabel('Fonte de Tráfego')

plt.subplot(1, 2, 2)
sns.barplot(x='fonte_trafego', y='taxa_conversao', data=desempenho, palette='viridis')
plt.title('Taxa de Conversão por Fonte de Tráfego')
plt.ylabel('Taxa de Conversão (%)')
plt.xlabel('Fonte de Tráfego')

plt.tight_layout()
plt.show()

print(desempenho)